//autentificación
export const LOGIN = "LOGIN";
export const CERRAR_SESION = "CERRAR_SESION";
export const AUTH_USUARIO = "AUTH_USUARIO";
export const CAMBIAR_CLAVE = "CAMBIAR_CLAVE";
export const ACTUALIZAR_USUARIO = "ACTUALIZAR_USUARIO";
export const RECUPERAR_CLAVE = "RECUPERAR_CLAVE";

//alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//usuarios
export const REGISTRO_USUARIO = "REGISTRO_USUARIO";
export const EDITAR_USUARIO = "EDITAR_USUARIO";
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const ELIMINAR_USUARIO = "ELIMINAR_USUARIO";
export const USUARIO_ACTUAL = "USUARIO_ACTUAL";

//ubicaciones
export const REGISTRO_UBICACION = "REGISTRO_UBICACION";
export const EDITAR_UBICACION = "EDITAR_UBICACION";
export const OBTENER_UBICACIONES = "OBTENER_UBICACIONES";
export const ELIMINAR_UBICACION = "ELIMINAR_UBICACION";
export const UBICACION_ACTUAL = "UBICACION_ACTUAL";

//activos   
export const REGISTRO_ACTIVO = "REGISTRO_ACTIVO";
export const EDITAR_ACTIVO = "EDITAR_ACTIVO";
export const OBTENER_ACTIVOS = "OBTENER_ACTIVOS";
export const ELIMINAR_ACTIVO = "ELIMINAR_ACTIVO";
export const ACTIVO_ACTUAL = "ACTIVO_ACTUAL";
export const CARGANDO_ACTIVOS = "CARGANDO_ACTIVOS";


//alertas
export const REGISTRAR_ALERTA = "REGISTRAR_ALERTA";
export const DESACTIVAR_ALERTA = "DESACTIVAR_ALERTA";
export const OBTENER_ALERTAS = "OBTENER_ALERTAS";
export const ALERTA_ACTUAL = "ALERTA_ACTUAL";


//Configuración Diseño
export const UPDATE_FONT_FAMILY = "UPDATE_FONT_FAMILY";
export const UPDATE_FONT_SIZE = "UPDATE_FONT_SIZE";
export const UPDATE_COLORS = "UPDATE_COLORS";
export const OBTENER_CONFIG_USUARIO = "OBTENER_CONFIG_USUARIO";